// ============================================================
// components/SuggestionsCard.jsx — AI improvement suggestions
// ============================================================
import { motion } from "framer-motion";
import { HiOutlineLightBulb } from "react-icons/hi2";
import { TbSparkles } from "react-icons/tb";

// Different accent colors cycling per suggestion
const accentColors = [
  { dot: "bg-cyan-400",   num: "text-cyan-400",   border: "border-cyan-500/15" },
  { dot: "bg-indigo-400", num: "text-indigo-400",  border: "border-indigo-500/15" },
  { dot: "bg-violet-400", num: "text-violet-400",  border: "border-violet-500/15" },
  { dot: "bg-sky-400",    num: "text-sky-400",     border: "border-sky-500/15" },
  { dot: "bg-teal-400",   num: "text-teal-400",    border: "border-teal-500/15" },
  { dot: "bg-blue-400",   num: "text-blue-400",    border: "border-blue-500/15" },
  { dot: "bg-purple-400", num: "text-purple-400",  border: "border-purple-500/15" },
  { dot: "bg-cyan-300",   num: "text-cyan-300",    border: "border-cyan-400/15" },
];

export default function SuggestionsCard({ suggestions }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6, delay: 0.25, ease: [0.22, 1, 0.36, 1] }}
      className="glass-card p-6"
    >
      {/* Header */}
      <div className="flex items-center justify-between mb-5">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-indigo-500/10 border border-indigo-500/25 flex items-center justify-center">
            <HiOutlineLightBulb className="w-4 h-4 text-indigo-400" />
          </div>
          <div>
            <p className="font-display font-semibold text-white text-sm">AI Suggestions</p>
            <p className="text-xs text-slate-500">Actionable improvements from Gemini</p>
          </div>
        </div>
        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-indigo-500/10 border border-indigo-500/20">
          <TbSparkles className="w-3 h-3 text-indigo-400" />
          <span className="text-indigo-400 text-xs font-mono font-semibold">{suggestions.length}</span>
        </div>
      </div>

      {/* Suggestions list */}
      {suggestions.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-8 text-center">
          <p className="text-sm text-slate-400">No suggestions at this time. Great resume!</p>
        </div>
      ) : (
        <div className="space-y-3">
          {suggestions.map((suggestion, i) => {
            const accent = accentColors[i % accentColors.length];
            return (
              <motion.div
                key={i}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.3 + i * 0.07, duration: 0.4 }}
                className={`suggestion-item border ${accent.border}`}
              >
                {/* Number badge */}
                <div className="flex-shrink-0 w-7 h-7 rounded-lg bg-white/5 border border-white/8 flex items-center justify-center">
                  <span className={`font-mono font-bold text-xs ${accent.num}`}>{i + 1}</span>
                </div>
                {/* Suggestion text */}
                <p className="text-sm text-slate-300 leading-relaxed">{suggestion}</p>
              </motion.div>
            );
          })}
        </div>
      )}

      {/* Footer note */}
      <div className="mt-5 flex items-start gap-2 p-3 rounded-xl bg-white/[0.02] border border-white/5">
        <TbSparkles className="w-4 h-4 text-indigo-400 flex-shrink-0 mt-0.5" />
        <p className="text-xs text-slate-600 leading-relaxed">
          These suggestions are generated by Gemini 1.5 Flash. Always review and tailor them to your unique experience and voice.
        </p>
      </div>
    </motion.div>
  );
}
